Algoritmo "Entrada e Saida de Dados"
// Descrição   : Entrada e Saida de Dados
// Autor(a)    : Fábio Sousa
// Data atual  : 09/12/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite o seu idade:")
   leia(nota)
   
   escreval("O nome digitado foi: ",nome)
   escreval("O idade digitado foi: ",nota)

Fimalgoritmo